language: python

cache: pip

python:
    - 3.5
    - 3.6

env:
    - DJANGO_VERSION=2.0.*

install:
    - pip install Django==$DJANGO_VERSION
    - pip install -e .
    - pip install -r requirements/requirements-test.txt

script:
    - flake8
    - pytest
    - mypy graphene_permissions --ignore-missing
